#include <Windows.h>

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <limits>
#include <span>
#include <string_view>

#include "../../core/filesystem/path.h"
#include "../../core/logging/log.h"
#include "../../core/settings/settings.h"
#include "../../state/build_data/abilities/ability_bucket_catalog.h"
#include "../../state/build_data/inventory/buckets/inventory_bucket_catalog.h"
#include "../../state/build_data/progressions/progression_catalog.h"
#include "../../state/build_data/socket_entry_lists/socket_entry_list_catalog.h"
#include "../../state/build_data/socket_entry_buckets/socket_entry_bucket_catalog.h"
#include "content_loader.h"

namespace sunrise::server::content {
namespace {

namespace abilities = state::build_data::abilities;
namespace buckets = state::build_data::inventory::buckets;
namespace progressions = state::build_data::progressions;
namespace socket_lists = state::build_data::socket_entry_lists;
namespace socket_entry_buckets = state::build_data::socket_entry_buckets;

/** One of the five decoded Option-B domain files, in swap order. */
struct DomainFile {
    std::string_view name;
    std::wstring_view file;
    enum class Kind {
        inventoryBuckets,
        socketEntryLists,
        socketEntryTables,
        abilityBuckets,
        progressions,
        socketEntryBuckets,
    } kind;
};

/** The six decoded domains the loader swaps after cache::load. */
constexpr std::array<DomainFile, 6> kDomainFiles{{
    {"inventoryBuckets",
     L"\\s1_domains_inventoryBuckets.json",
     DomainFile::Kind::inventoryBuckets},
    {"socketEntryLists",
     L"\\s1_domains_socketEntryLists.json",
     DomainFile::Kind::socketEntryLists},
    {"socketEntryTables",
     L"\\s1_domains_socketEntryTables.json",
     DomainFile::Kind::socketEntryTables},
    {"abilityBuckets", L"\\s1_domains_abilityBuckets.json", DomainFile::Kind::abilityBuckets},
    {"progressions", L"\\s1_domains_progressions.json", DomainFile::Kind::progressions},
    {"socketEntryBuckets",
     L"\\s1_domains_socketEntryBuckets.json",
     DomainFile::Kind::socketEntryBuckets},
}};

/** The generated domain files stay far under this fixed read buffer. */
constexpr std::size_t kJsonCapacity = 2 * 1024 * 1024;
/** Largest JSON value count the fixed parser arena accepts. */
constexpr std::size_t kNodeCapacity = 262144;
/** Sentinel arena index meaning "not present". */
constexpr std::size_t kNpos = (std::numeric_limits<std::size_t>::max)();

// ---------------------------------------------------------------------------
// Minimal JSON parser over the deterministic domain-file shape (generated by the S1-3
// decode lane's Python emitter): objects, arrays, integers, and plain ASCII strings.
// Anything else (escapes, floats, deep nesting) is refused.
//
// Arena model: one fixed node arena. A container's children are LINKED through each
// child's nextChild field (objects link their keys; arrays link their elements), because
// a child value that is itself a container appends its own descendants into the arena
// between the parent's children. An object member's value node always sits exactly one
// arena slot after its key node (value() appends the value node before any descendants).
// ---------------------------------------------------------------------------

/** One parsed JSON value. Objects link keys via nextChild; arrays link elements. */
struct Node {
    enum class Kind : std::uint8_t { invalid, null, boolean, number, string, array, object };

    Kind kind{Kind::invalid};
    bool booleanValue{};
    std::int64_t numberValue{};
    std::string_view text{};
    std::size_t firstChild{kNpos};
    std::size_t childCount{};
    std::size_t nextChild{kNpos};
};

/** @return One array element by position, or npos. */
[[nodiscard]] std::size_t element(std::span<Node> nodes,
                                  std::size_t arrayNode,
                                  std::size_t index) noexcept {
    const Node& array = nodes[arrayNode];
    if (array.kind != Node::Kind::array || index >= array.childCount) {
        return kNpos;
    }
    std::size_t node = array.firstChild;
    for (std::size_t step = 0; step < index; ++step) {
        if (node == kNpos || node >= nodes.size()) {
            return kNpos;
        }
        node = nodes[node].nextChild;
    }
    return node < nodes.size() ? node : kNpos;
}

/** @return Index of one object member's value node, or npos. */
[[nodiscard]] std::size_t find_member(std::span<Node> nodes,
                                      std::size_t objectNode,
                                      std::string_view name) noexcept {
    const Node& object = nodes[objectNode];
    if (object.kind != Node::Kind::object) {
        return kNpos;
    }
    std::size_t key = object.firstChild;
    while (key != kNpos && key < nodes.size()) {
        const Node& keyNode = nodes[key];
        const std::size_t value = key + 1;
        if (keyNode.kind == Node::Kind::string && keyNode.text == name
            && value < nodes.size()) {
            return value;
        }
        key = keyNode.nextChild;
    }
    return kNpos;
}

/** Reads one required nonnegative integer member inside its maximum. */
[[nodiscard]] bool member_number(std::span<Node> nodes,
                                 std::size_t objectNode,
                                 std::string_view name,
                                 std::uint64_t& output,
                                 std::uint64_t maximum) noexcept {
    const std::size_t member = find_member(nodes, objectNode, name);
    if (member == kNpos) {
        return false;
    }
    const Node& value = nodes[member];
    if (value.kind != Node::Kind::number || value.numberValue < 0) {
        return false;
    }
    const auto number = static_cast<std::uint64_t>(value.numberValue);
    if (number > maximum) {
        return false;
    }
    output = number;
    return true;
}

/** Reads one required string member. */
[[nodiscard]] bool member_string(std::span<Node> nodes,
                                 std::size_t objectNode,
                                 std::string_view name,
                                 std::string_view& output) noexcept {
    const std::size_t member = find_member(nodes, objectNode, name);
    if (member == kNpos) {
        return false;
    }
    const Node& value = nodes[member];
    if (value.kind != Node::Kind::string) {
        return false;
    }
    output = value.text;
    return true;
}

/** @return Index of one required array member, or npos. */
[[nodiscard]] std::size_t member_array(std::span<Node> nodes,
                                       std::size_t objectNode,
                                       std::string_view name) noexcept {
    const std::size_t member = find_member(nodes, objectNode, name);
    if (member == kNpos || nodes[member].kind != Node::Kind::array) {
        return kNpos;
    }
    return member;
}

/** Reads one array element as a nonnegative integer inside its maximum. */
[[nodiscard]] bool element_number(std::span<Node> nodes,
                                  std::size_t arrayNode,
                                  std::size_t index,
                                  std::uint64_t& output,
                                  std::uint64_t maximum) noexcept {
    const std::size_t elementNode = element(nodes, arrayNode, index);
    if (elementNode == kNpos) {
        return false;
    }
    const Node& value = nodes[elementNode];
    if (value.kind != Node::Kind::number || value.numberValue < 0) {
        return false;
    }
    const auto number = static_cast<std::uint64_t>(value.numberValue);
    if (number > maximum) {
        return false;
    }
    output = number;
    return true;
}

/** Parses "0x" + up to 8 hex digits into a 32-bit plug-source hash. */
[[nodiscard]] bool parse_hex_u32(std::string_view text, std::uint32_t& output) noexcept {
    if (text.size() < 3 || text[0] != '0' || (text[1] != 'x' && text[1] != 'X')) {
        return false;
    }
    std::uint32_t value = 0;
    for (std::size_t index = 2; index < text.size(); ++index) {
        const char digit = text[index];
        unsigned nibble = 0;
        if (digit >= '0' && digit <= '9') {
            nibble = static_cast<unsigned>(digit - '0');
        } else if (digit >= 'a' && digit <= 'f') {
            nibble = static_cast<unsigned>(digit - 'a') + 10;
        } else if (digit >= 'A' && digit <= 'F') {
            nibble = static_cast<unsigned>(digit - 'A') + 10;
        } else {
            return false;
        }
        value = value * 16 + nibble;
    }
    output = value;
    return true;
}

/** Bounded recursive-descent parser over one domain file's JSON text. */
class Parser final {
public:
    Parser(std::string_view input, std::span<Node> nodes) noexcept : input_(input), nodes_(nodes) {}

    /** Parses one complete document into the arena root. */
    [[nodiscard]] bool parse(std::size_t& root) noexcept {
        if (nodes_.empty()) {
            return false;
        }
        skip_whitespace();
        root = 0;
        if (!value(root)) {
            return false;
        }
        skip_whitespace();
        return position_ == input_.size();
    }

    /** @return Current parse position, for failure diagnostics. */
    [[nodiscard]] std::size_t position() const noexcept {
        return position_;
    }

    /** @return One input byte at an index, or 0 past the end. */
    [[nodiscard]] std::uint8_t byte_at(std::size_t index) const noexcept {
        return index < input_.size() ? static_cast<std::uint8_t>(input_[index]) : 0;
    }

private:
    [[nodiscard]] bool value(std::size_t& node) noexcept {
        skip_whitespace();
        if (position_ >= input_.size()) {
            return false;
        }
        const char next = input_[position_];
        if (next == '{') {
            return object(node);
        }
        if (next == '[') {
            return array(node);
        }
        if (next == '"') {
            return string(node);
        }
        if (next == 't' || next == 'f') {
            return literal(node, "true", true) || literal(node, "false", false);
        }
        if (next == 'n') {
            return literal(node, "null", false);
        }
        return number(node);
    }

    [[nodiscard]] bool object(std::size_t& node) noexcept {
        if (!consume('{')) {
            return false;
        }
        const std::size_t container = append(Node::Kind::object);
        if (container == kNpos) {
            return false;
        }
        if (consume('}')) {
            node = container;
            return true;
        }
        std::size_t previousKey = kNpos;
        for (;;) {
            std::size_t key = 0;
            std::size_t member = 0;
            if (!string(key) || !consume(':') || !value(member)) {
                return false;
            }
            // The member value node is the first node value() appends, so it always sits right
            // after its key node; keys form the member chain.
            Node& containerNode = nodes_[container];
            if (previousKey == kNpos) {
                containerNode.firstChild = key;
            } else {
                nodes_[previousKey].nextChild = key;
            }
            previousKey = key;
            ++containerNode.childCount;
            if (consume('}')) {
                break;
            }
            if (!consume(',')) {
                return false;
            }
        }
        node = container;
        return true;
    }

    [[nodiscard]] bool array(std::size_t& node) noexcept {
        if (!consume('[')) {
            return false;
        }
        const std::size_t container = append(Node::Kind::array);
        if (container == kNpos) {
            return false;
        }
        if (consume(']')) {
            node = container;
            return true;
        }
        std::size_t previousElement = kNpos;
        for (;;) {
            std::size_t elementNode = 0;
            if (!value(elementNode)) {
                return false;
            }
            Node& containerNode = nodes_[container];
            if (previousElement == kNpos) {
                containerNode.firstChild = elementNode;
            } else {
                nodes_[previousElement].nextChild = elementNode;
            }
            previousElement = elementNode;
            ++containerNode.childCount;
            if (consume(']')) {
                break;
            }
            if (!consume(',')) {
                return false;
            }
        }
        node = container;
        return true;
    }

    [[nodiscard]] bool string(std::size_t& node) noexcept {
        skip_whitespace();
        if (position_ >= input_.size() || input_[position_] != '"') {
            return false;
        }
        const std::size_t start = ++position_;
        while (position_ < input_.size() && input_[position_] != '"') {
            // The generated domain files carry plain ASCII; an escape would mean an unexpected
            // producer and is refused.
            if (input_[position_] == '\\') {
                return false;
            }
            ++position_;
        }
        if (position_ >= input_.size()) {
            return false;
        }
        const std::string_view text = input_.substr(start, position_ - start);
        ++position_;
        const std::size_t index = append(Node::Kind::string);
        if (index == kNpos) {
            return false;
        }
        nodes_[index].text = text;
        node = index;
        return true;
    }

    [[nodiscard]] bool number(std::size_t& node) noexcept {
        const std::size_t start = position_;
        if (position_ < input_.size() && input_[position_] == '-') {
            ++position_;
        }
        if (position_ >= input_.size() || !is_digit(input_[position_])) {
            position_ = start;
            return false;
        }
        std::uint64_t magnitude = 0;
        while (position_ < input_.size() && is_digit(input_[position_])) {
            magnitude = magnitude * 10 + static_cast<std::uint64_t>(input_[position_] - '0');
            if (magnitude > static_cast<std::uint64_t>((std::numeric_limits<std::int64_t>::max)())) {
                position_ = start;
                return false;
            }
            ++position_;
        }
        // The generated domain files carry integers only.
        if (position_ < input_.size()
            && (input_[position_] == '.' || input_[position_] == 'e' || input_[position_] == 'E')) {
            position_ = start;
            return false;
        }
        const std::size_t index = append(Node::Kind::number);
        if (index == kNpos) {
            return false;
        }
        const bool negative = start < position_ && input_[start] == '-';
        nodes_[index].numberValue =
            negative ? -static_cast<std::int64_t>(magnitude) : static_cast<std::int64_t>(magnitude);
        node = index;
        return true;
    }

    [[nodiscard]] bool literal(std::size_t& node,
                               std::string_view text,
                               bool booleanValue) noexcept {
        if (input_.substr(position_, text.size()) != text) {
            return false;
        }
        position_ += text.size();
        const std::size_t index = append(Node::Kind::boolean);
        if (index == kNpos) {
            return false;
        }
        nodes_[index].booleanValue = booleanValue;
        node = index;
        return true;
    }

    [[nodiscard]] std::size_t append(Node::Kind kind) noexcept {
        if (nodeCount_ >= nodes_.size()) {
            return kNpos;
        }
        nodes_[nodeCount_] = Node{kind};
        return nodeCount_++;
    }

    [[nodiscard]] bool consume(char expected) noexcept {
        skip_whitespace();
        if (position_ >= input_.size() || input_[position_] != expected) {
            return false;
        }
        ++position_;
        return true;
    }

    void skip_whitespace() noexcept {
        while (position_ < input_.size()) {
            const char value = input_[position_];
            if (value != ' ' && value != '\t' && value != '\r' && value != '\n') {
                return;
            }
            ++position_;
        }
    }

    [[nodiscard]] static bool is_digit(char value) noexcept {
        return value >= '0' && value <= '9';
    }

    std::string_view input_;
    std::span<Node> nodes_;
    std::size_t position_{};
    std::size_t nodeCount_{};
};

// ---------------------------------------------------------------------------
// Parsed row storage (fixed arrays; the socket-list capacity would overflow the 1 MiB
// stack if allocated per call, so the loader's row storage is process-lifetime — the
// loader runs once at boot, single-threaded).
// ---------------------------------------------------------------------------

struct BucketRows {
    std::array<buckets::Descriptor, buckets::kDescriptorCapacity> rows{};
    std::size_t count{};
};

struct SocketListRows {
    std::array<socket_lists::Definition, socket_lists::kDefinitionCapacity> rows{};
    std::size_t count{};
};

struct EntryTableRows {
    std::array<socket_lists::EntryTable, socket_lists::kEntryTableCapacity> rows{};
    std::size_t count{};
};

struct AbilityRows {
    std::array<abilities::Definition, abilities::kDefinitionCapacity> rows{};
    std::size_t count{};
};

struct ProgressionRows {
    std::array<progressions::Definition, progressions::kDefinitionCapacity> rows{};
    std::size_t count{};
};

struct SocketEntryBucketRows {
    std::array<socket_entry_buckets::Definition, socket_entry_buckets::kDefinitionCapacity> rows{};
    std::size_t count{};
};

// ---------------------------------------------------------------------------
// Reporting (defined before the row extractors, which use it for diagnostics).
// ---------------------------------------------------------------------------

/** Emits one validation line on the console and through the log. */
void report(std::string_view line) noexcept {
    std::fwrite(line.data(), 1, line.size(), stdout);
    std::fputc('\n', stdout);
    std::fflush(stdout);
    core::log::write(core::log::Channel::state, core::log::Level::info, line);
}

/** Emits one loader failure line naming the domain and the failing step. */
void report_fail(std::string_view domain, std::string_view reason) noexcept {
    std::array<char, 192> line{};
    const int written = std::snprintf(line.data(),
                                      line.size(),
                                      "ev=s1_loader stage=swap domain=%.*s result=fail "
                                      "reason=%.*s",
                                      static_cast<int>(domain.size()),
                                      domain.data(),
                                      static_cast<int>(reason.size()),
                                      reason.data());
    if (written > 0) {
        report({line.data(), static_cast<std::size_t>(written)});
    }
}

// ---------------------------------------------------------------------------
// Row extraction + S1RD-08 canonicalization.
// ---------------------------------------------------------------------------

/** Parses the bucket descriptors and sorts them by bucketId (S1RD-08). */
[[nodiscard]] bool parse_buckets(std::span<Node> nodes,
                                 std::size_t rowsNode,
                                 BucketRows& output) noexcept {
    const Node& rows = nodes[rowsNode];
    if (rows.kind != Node::Kind::array || rows.childCount == 0) {
        return false;
    }
    output.count = 0;
    for (std::size_t index = 0; index < rows.childCount; ++index) {
        if (output.count >= output.rows.size()) {
            return false;
        }
        const std::size_t rowNode = element(nodes, rowsNode, index);
        if (rowNode == kNpos || nodes[rowNode].kind != Node::Kind::object) {
            return false;
        }
        std::uint64_t bucketId = 0;
        std::uint64_t selector = 0;
        std::uint64_t firstSlot = 0;
        std::uint64_t slotCount = 0;
        if (!member_number(nodes, rowNode, "bucketId", bucketId, 0xFF)
            || !member_number(nodes, rowNode, "arraySelector", selector, 0xFF)
            || !member_number(nodes, rowNode, "firstSlot", firstSlot, 0xFFFF)
            || !member_number(nodes, rowNode, "slotCount", slotCount, 0xFFFF)) {
            return false;
        }
        output.rows[output.count] = {
            static_cast<std::uint8_t>(bucketId),
            static_cast<buckets::ArraySelector>(selector),
            static_cast<std::uint16_t>(firstSlot),
            static_cast<std::uint16_t>(slotCount),
        };
        ++output.count;
    }
    std::sort(output.rows.begin(),
              output.rows.begin() + static_cast<std::ptrdiff_t>(output.count),
              [](const buckets::Descriptor& left, const buckets::Descriptor& right) {
                  return left.bucketId < right.bucketId;
              });
    return true;
}

/** Parses the dense socket-entry-list rows and sorts them by definitionIndex. */
[[nodiscard]] bool parse_socket_lists(std::span<Node> nodes,
                                      std::size_t rowsNode,
                                      SocketListRows& output) noexcept {
    const Node& rows = nodes[rowsNode];
    if (rows.kind != Node::Kind::array || rows.childCount == 0) {
        return false;
    }
    output.count = 0;
    for (std::size_t index = 0; index < rows.childCount; ++index) {
        if (output.count >= output.rows.size()) {
            return false;
        }
        const std::size_t rowNode = element(nodes, rowsNode, index);
        if (rowNode == kNpos || nodes[rowNode].kind != Node::Kind::object) {
            return false;
        }
        std::uint64_t definitionHash = 0;
        std::uint64_t definitionIndex = 0;
        std::uint64_t entryCount = 0;
        std::uint64_t readyMask = 0;
        if (!member_number(nodes, rowNode, "definitionHash", definitionHash, 0xFFFFFFFFULL)
            || !member_number(nodes, rowNode, "definitionIndex", definitionIndex, 0xFFFF)
            || !member_number(nodes, rowNode, "entryCount", entryCount, 0xFF)
            || !member_number(nodes, rowNode, "readyMask", readyMask,
                              (std::numeric_limits<std::uint64_t>::max)())) {
            return false;
        }
        output.rows[output.count] = {
            static_cast<std::uint32_t>(definitionHash),
            static_cast<std::uint16_t>(definitionIndex),
            static_cast<std::uint8_t>(entryCount),
            readyMask,
        };
        ++output.count;
    }
    std::sort(output.rows.begin(),
              output.rows.begin() + static_cast<std::ptrdiff_t>(output.count),
              [](const socket_lists::Definition& left, const socket_lists::Definition& right) {
                  return left.definitionIndex < right.definitionIndex;
              });
    return true;
}

/** Parses the per-list entry tables, padding every tail with the default Entry (S1RD-08). */
[[nodiscard]] bool parse_entry_tables(std::span<Node> nodes,
                                      std::size_t rowsNode,
                                      EntryTableRows& output) noexcept {
    const Node& rows = nodes[rowsNode];
    if (rows.kind != Node::Kind::array || rows.childCount == 0) {
        return false;
    }
    output.count = 0;
    for (std::size_t index = 0; index < rows.childCount; ++index) {
        if (output.count >= output.rows.size()) {
            return false;
        }
        const std::size_t rowNode = element(nodes, rowsNode, index);
        if (rowNode == kNpos || nodes[rowNode].kind != Node::Kind::object) {
            return false;
        }
        std::uint64_t definitionIndex = 0;
        std::uint64_t entryCount = 0;
        if (!member_number(nodes, rowNode, "definitionIndex", definitionIndex, 0xFFFF)
            || !member_number(nodes, rowNode, "entryCount", entryCount,
                              socket_lists::kEntryCapacity)) {
            return false;
        }
        const std::size_t entriesNode = member_array(nodes, rowNode, "entries");
        if (entriesNode == kNpos || nodes[entriesNode].childCount != entryCount) {
            return false;
        }
        socket_lists::EntryTable table{};
        table.definitionIndex = static_cast<std::uint16_t>(definitionIndex);
        for (std::size_t entry = 0; entry < entryCount; ++entry) {
            const std::size_t entryNode = element(nodes, entriesNode, entry);
            if (entryNode == kNpos || nodes[entryNode].kind != Node::Kind::object) {
                return false;
            }
            std::string_view plugSourceText;
            std::uint64_t group = 0;
            std::uint64_t kind = 0;
            std::uint32_t plugSource = 0;
            if (!member_string(nodes, entryNode, "plugSource", plugSourceText)
                || !parse_hex_u32(plugSourceText, plugSource)
                || !member_number(nodes, entryNode, "group", group, 0xFF)
                || !member_number(nodes, entryNode, "kind", kind, 0xFF)) {
                return false;
            }
            table.entries[entry] = {
                plugSource,
                static_cast<std::uint8_t>(group),
                static_cast<std::uint8_t>(kind),
            };
        }
        // The EntryTable aggregate default is exactly the cache's padded tail row
        // {plugSource 0, group 0xFF, kind 0}, so lanes entryCount..35 stay defaulted.
        output.rows[output.count] = table;
        ++output.count;
    }
    std::sort(output.rows.begin(),
              output.rows.begin() + static_cast<std::ptrdiff_t>(output.count),
              [](const socket_lists::EntryTable& left, const socket_lists::EntryTable& right) {
                  return left.definitionIndex < right.definitionIndex;
              });
    return true;
}

/** Parses the ability-bucket rows and sorts them into the cache's ability_less order. */
[[nodiscard]] bool parse_ability_rows(std::span<Node> nodes,
                                      std::size_t rowsNode,
                                      AbilityRows& output) noexcept {
    const Node& rows = nodes[rowsNode];
    if (rows.kind != Node::Kind::array || rows.childCount == 0) {
        return false;
    }
    output.count = 0;
    for (std::size_t index = 0; index < rows.childCount; ++index) {
        if (output.count >= output.rows.size()) {
            return false;
        }
        const std::size_t rowNode = element(nodes, rowsNode, index);
        if (rowNode == kNpos || nodes[rowNode].kind != Node::Kind::object) {
            return false;
        }
        std::uint64_t socketEntryListIndex = 0;
        if (!member_number(nodes, rowNode, "socketEntryListIndex", socketEntryListIndex, 0xFFFF)) {
            return false;
        }
        const std::size_t selectionNode = member_array(nodes, rowNode, "selection");
        if (selectionNode == kNpos || nodes[selectionNode].childCount != 5) {
            return false;
        }
        std::uint64_t selection[5] = {};
        for (std::size_t lane = 0; lane < 5; ++lane) {
            if (!element_number(nodes, selectionNode, lane, selection[lane], 0xFF)) {
                return false;
            }
        }
        const std::size_t overflowNode = member_array(nodes, rowNode, "overflow");
        if (overflowNode == kNpos
            || nodes[overflowNode].childCount > abilities::kOverflowCapacity) {
            return false;
        }
        const std::size_t bucketsNode = member_array(nodes, rowNode, "buckets");
        if (bucketsNode == kNpos
            || nodes[bucketsNode].childCount != abilities::kBucketCapacity) {
            return false;
        }

        abilities::Definition definition{};
        definition.socketEntryListIndex = static_cast<std::uint16_t>(socketEntryListIndex);
        definition.selection = {
            static_cast<std::uint8_t>(selection[0]),
            static_cast<std::uint8_t>(selection[1]),
            static_cast<std::uint8_t>(selection[2]),
            static_cast<std::uint8_t>(selection[3]),
            static_cast<std::uint8_t>(selection[4]),
        };
        definition.overflowCount = static_cast<std::uint8_t>(nodes[overflowNode].childCount);
        for (std::size_t lane = 0; lane < nodes[overflowNode].childCount; ++lane) {
            std::uint64_t hash = 0;
            if (!element_number(nodes, overflowNode, lane, hash, 0xFFFFFFFFULL)) {
                return false;
            }
            definition.overflow[lane] = static_cast<std::uint32_t>(hash);
        }
        for (std::size_t bucket = 0; bucket < abilities::kBucketCapacity; ++bucket) {
            const std::size_t bucketNode = element(nodes, bucketsNode, bucket);
            if (bucketNode == kNpos || nodes[bucketNode].kind != Node::Kind::object) {
                return false;
            }
            std::uint64_t kind = 0;
            if (!member_number(nodes, bucketNode, "kind", kind, 0xFF)) {
                return false;
            }
            const std::size_t hashesNode = member_array(nodes, bucketNode, "hashes");
            if (hashesNode == kNpos
                || nodes[hashesNode].childCount > abilities::kBucketHashCapacity) {
                return false;
            }
            abilities::Bucket& target = definition.buckets[bucket];
            target.kind = static_cast<std::uint8_t>(kind);
            target.hashCount = static_cast<std::uint8_t>(nodes[hashesNode].childCount);
            for (std::size_t hash = 0; hash < nodes[hashesNode].childCount; ++hash) {
                std::uint64_t value = 0;
                if (!element_number(nodes, hashesNode, hash, value, 0xFFFFFFFFULL)) {
                    return false;
                }
                target.hashes[hash] = static_cast<std::uint32_t>(value);
            }
        }
        output.rows[output.count] = definition;
        ++output.count;
    }
    const auto selectionKey = [](const abilities::Selection& selection) noexcept {
        return std::array<std::uint8_t, 5>{selection.movementEntry,
                                           selection.grenadeEntry,
                                           selection.superEntry,
                                           selection.meleeEntry,
                                           selection.classEntry};
    };
    std::sort(output.rows.begin(),
              output.rows.begin() + static_cast<std::ptrdiff_t>(output.count),
              [&selectionKey](const abilities::Definition& left,
                              const abilities::Definition& right) {
                  if (left.socketEntryListIndex != right.socketEntryListIndex) {
                      return left.socketEntryListIndex < right.socketEntryListIndex;
                  }
                  return selectionKey(left.selection) < selectionKey(right.selection);
              });
    return true;
}

/** Parses the progression rows, reducing the native scope (S1RD-08). */
[[nodiscard]] bool parse_progressions(std::span<Node> nodes,
                                      std::size_t rowsNode,
                                      ProgressionRows& output) noexcept {
    const Node& rows = nodes[rowsNode];
    if (rows.kind != Node::Kind::array || rows.childCount == 0) {
        return false;
    }
    output.count = 0;
    for (std::size_t index = 0; index < rows.childCount; ++index) {
        if (output.count >= output.rows.size()) {
            return false;
        }
        const std::size_t rowNode = element(nodes, rowsNode, index);
        if (rowNode == kNpos || nodes[rowNode].kind != Node::Kind::object) {
            return false;
        }
        std::uint64_t definitionIndex = 0;
        std::uint64_t scopeRaw = 0;
        if (!member_number(nodes, rowNode, "definitionIndex", definitionIndex, 0xFFFF)
            || !member_number(nodes, rowNode, "scopeRaw", scopeRaw, 0xFF)) {
            return false;
        }
        const std::uint8_t reduced =
            scopeRaw <= static_cast<std::uint64_t>(progressions::Scope::character)
                ? static_cast<std::uint8_t>(scopeRaw)
                : static_cast<std::uint8_t>(progressions::Scope::unreplicated);
        // Cross-check the emitter's own reduction so both producers cannot drift silently.
        std::uint64_t emittedScope = 0;
        if (member_number(nodes, rowNode, "scope", emittedScope, 0xFF)
            && emittedScope != reduced) {
            return false;
        }
        output.rows[output.count] = {
            static_cast<std::uint16_t>(definitionIndex),
            static_cast<progressions::Scope>(reduced),
        };
        ++output.count;
    }
    std::sort(output.rows.begin(),
              output.rows.begin() + static_cast<std::ptrdiff_t>(output.count),
              [](const progressions::Definition& left, const progressions::Definition& right) {
                  return left.definitionIndex < right.definitionIndex;
              });
    return true;
}

// ---------------------------------------------------------------------------
// Row equality (JSON side vs cache-loaded runtime side, both canonicalized).
// ---------------------------------------------------------------------------

[[nodiscard]] bool bucket_rows_equal(const buckets::Descriptor& left,
                                     const buckets::Descriptor& right) noexcept {
    return left.bucketId == right.bucketId && left.arraySelector == right.arraySelector
           && left.firstSlot == right.firstSlot && left.slotCount == right.slotCount;
}

[[nodiscard]] bool socket_list_rows_equal(const socket_lists::Definition& left,
                                          const socket_lists::Definition& right) noexcept {
    return left.definitionHash == right.definitionHash
           && left.definitionIndex == right.definitionIndex
           && left.entryCount == right.entryCount && left.readyMask == right.readyMask;
}

[[nodiscard]] bool entry_table_rows_equal(const socket_lists::EntryTable& left,
                                          const socket_lists::EntryTable& right) noexcept {
    if (left.definitionIndex != right.definitionIndex) {
        return false;
    }
    for (std::size_t index = 0; index < socket_lists::kEntryCapacity; ++index) {
        if (left.entries[index].plugSource != right.entries[index].plugSource
            || left.entries[index].group != right.entries[index].group
            || left.entries[index].kind != right.entries[index].kind) {
            return false;
        }
    }
    return true;
}

[[nodiscard]] bool ability_rows_equal(const abilities::Definition& left,
                                      const abilities::Definition& right) noexcept {
    if (left.socketEntryListIndex != right.socketEntryListIndex
        || left.selection != right.selection || left.overflowCount != right.overflowCount) {
        return false;
    }
    for (std::size_t bucket = 0; bucket < abilities::kBucketCapacity; ++bucket) {
        const abilities::Bucket& leftBucket = left.buckets[bucket];
        const abilities::Bucket& rightBucket = right.buckets[bucket];
        if (leftBucket.kind != rightBucket.kind
            || leftBucket.hashCount != rightBucket.hashCount) {
            return false;
        }
        for (std::size_t hash = 0; hash < abilities::kBucketHashCapacity; ++hash) {
            if (leftBucket.hashes[hash] != rightBucket.hashes[hash]) {
                return false;
            }
        }
    }
    for (std::size_t overflow = 0; overflow < abilities::kOverflowCapacity; ++overflow) {
        if (left.overflow[overflow] != right.overflow[overflow]) {
            return false;
        }
    }
    return true;
}

[[nodiscard]] bool progression_rows_equal(const progressions::Definition& left,
                                          const progressions::Definition& right) noexcept {
    return left.definitionIndex == right.definitionIndex && left.scope == right.scope;
}

// ---------------------------------------------------------------------------
// Swap drivers.
// ---------------------------------------------------------------------------

/** Emits the S1-3 swap validation line for one domain. */
void report_swap(std::string_view domain,
                 std::size_t jsonCount,
                 std::size_t cacheCount,
                 bool match) noexcept {
    std::array<char, 192> line{};
    const int written = std::snprintf(line.data(),
                                      line.size(),
                                      "ev=s1_loader stage=swap domain=%.*s json=%zu cache=%zu "
                                      "result=%s",
                                      static_cast<int>(domain.size()),
                                      domain.data(),
                                      jsonCount,
                                      cacheCount,
                                      match ? "match" : "mismatch");
    if (written > 0) {
        report({line.data(), static_cast<std::size_t>(written)});
    }
}

/** Reports the exact ability-bucket divergence that stops the boot. */
void report_ability_diff(const AbilityRows& parsed,
                         std::span<const abilities::Definition> cached,
                         std::size_t cachedCount) noexcept {
    const std::size_t common = (std::min)(parsed.count, cachedCount);
    std::size_t first = 0;
    while (first < common && ability_rows_equal(parsed.rows[first], cached[first])) {
        ++first;
    }
    std::array<char, 192> line{};
    const int written =
        std::snprintf(line.data(),
                      line.size(),
                      "ev=s1_loader stage=swap domain=abilityBuckets result=differ "
                      "json_rows=%zu cache_rows=%zu first_diff_row=%zu",
                      parsed.count,
                      cachedCount,
                      first);
    if (written > 0) {
        report({line.data(), static_cast<std::size_t>(written)});
    }
    if (first < common) {
        const abilities::Definition& parsedRow = parsed.rows[first];
        const abilities::Definition& cachedRow = cached[first];
        std::array<char, 192> detail{};
        const int detailWritten = std::snprintf(
            detail.data(),
            detail.size(),
            "ev=s1_loader stage=swap domain=abilityBuckets result=differ row=%zu "
            "json_list=%u cache_list=%u json_sel=%u,%u,%u,%u,%u cache_sel=%u,%u,%u,%u,%u",
            first,
            static_cast<unsigned>(parsedRow.socketEntryListIndex),
            static_cast<unsigned>(cachedRow.socketEntryListIndex),
            static_cast<unsigned>(parsedRow.selection.movementEntry),
            static_cast<unsigned>(parsedRow.selection.grenadeEntry),
            static_cast<unsigned>(parsedRow.selection.superEntry),
            static_cast<unsigned>(parsedRow.selection.meleeEntry),
            static_cast<unsigned>(parsedRow.selection.classEntry),
            static_cast<unsigned>(cachedRow.selection.movementEntry),
            static_cast<unsigned>(cachedRow.selection.grenadeEntry),
            static_cast<unsigned>(cachedRow.selection.superEntry),
            static_cast<unsigned>(cachedRow.selection.meleeEntry),
            static_cast<unsigned>(cachedRow.selection.classEntry));
        if (detailWritten > 0) {
            report({detail.data(), static_cast<std::size_t>(detailWritten)});
        }
    }
}

/** @return True when every parsed row equals the cache-loaded runtime rows. */
template <typename Row, typename Equal>
[[nodiscard]] bool rows_match(const Row* parsed,
                              std::size_t parsedCount,
                              const Row* cached,
                              std::size_t cachedCount,
                              Equal equal) noexcept {
    if (parsedCount != cachedCount) {
        return false;
    }
    for (std::size_t index = 0; index < parsedCount; ++index) {
        if (!equal(parsed[index], cached[index])) {
            return false;
        }
    }
    return true;
}

/** Swaps the inventory-bucket descriptors from the JSON over the cache rows. */
[[nodiscard]] bool swap_buckets(std::span<Node> nodes, std::size_t rowsNode) noexcept {
    static BucketRows parsed{};
    static std::array<buckets::Descriptor, buckets::kDescriptorCapacity> cached{};
    if (!parse_buckets(nodes, rowsNode, parsed)) {
        report_fail("inventoryBuckets", "parse");
        return false;
    }
    std::size_t cachedCount = 0;
    const bool match =
        buckets::snapshot(cached, cachedCount)
        && rows_match(parsed.rows.data(),
                      parsed.count,
                      cached.data(),
                      cachedCount,
                      bucket_rows_equal);
    report_swap("inventoryBuckets", parsed.count, cachedCount, match);
    if (!buckets::replace(std::span(parsed.rows).first(parsed.count))) {
        report_fail("inventoryBuckets", "reject");
        return false;
    }
    return true;
}

/** Swaps the dense socket-entry-list rows from the JSON over the cache rows. */
[[nodiscard]] bool swap_socket_lists(std::span<Node> nodes, std::size_t rowsNode) noexcept {
    static SocketListRows parsed{};
    static std::array<socket_lists::Definition, socket_lists::kDefinitionCapacity> cached{};
    if (!parse_socket_lists(nodes, rowsNode, parsed)) {
        report_fail("socketEntryLists", "parse");
        return false;
    }
    std::size_t cachedCount = 0;
    const bool match =
        socket_lists::snapshot(cached, cachedCount)
        && rows_match(parsed.rows.data(),
                      parsed.count,
                      cached.data(),
                      cachedCount,
                      socket_list_rows_equal);
    report_swap("socketEntryLists", parsed.count, cachedCount, match);
    if (!socket_lists::replace(std::span(parsed.rows).first(parsed.count))) {
        report_fail("socketEntryLists", "reject");
        return false;
    }
    return true;
}

/** Swaps the per-list entry tables from the JSON over the cache rows. */
[[nodiscard]] bool swap_entry_tables(std::span<Node> nodes, std::size_t rowsNode) noexcept {
    static EntryTableRows parsed{};
    static std::array<socket_lists::EntryTable, socket_lists::kEntryTableCapacity> cached{};
    if (!parse_entry_tables(nodes, rowsNode, parsed)) {
        report_fail("socketEntryTables", "parse");
        return false;
    }
    std::size_t cachedCount = 0;
    const bool match =
        socket_lists::snapshot_entry_tables(cached, cachedCount)
        && rows_match(parsed.rows.data(),
                      parsed.count,
                      cached.data(),
                      cachedCount,
                      entry_table_rows_equal);
    report_swap("socketEntryTables", parsed.count, cachedCount, match);
    if (!socket_lists::replace_entry_tables(std::span(parsed.rows).first(parsed.count))) {
        report_fail("socketEntryTables", "reject");
        return false;
    }
    return true;
}

/** Parses the resolved per-entry ability-bucket rows (the pure JSON domain — no cache
 *  counterpart; the rows replace the catalog outright). */
[[nodiscard]] bool parse_socket_entry_bucket_rows(std::span<Node> nodes,
                                                  std::size_t rowsNode,
                                                  SocketEntryBucketRows& output) noexcept {
    const Node& rows = nodes[rowsNode];
    if (rows.kind != Node::Kind::array || rows.childCount == 0) {
        return false;
    }
    output.count = 0;
    for (std::size_t index = 0; index < rows.childCount; ++index) {
        if (output.count >= output.rows.size()) {
            return false;
        }
        const std::size_t rowNode = element(nodes, rowsNode, index);
        if (rowNode == kNpos || nodes[rowNode].kind != Node::Kind::object) {
            return false;
        }
        std::uint64_t socketEntryListIndex = 0;
        if (!member_number(nodes, rowNode, "socketEntryListIndex", socketEntryListIndex, 0xFFFF)) {
            return false;
        }
        const std::size_t bucketsNode = member_array(nodes, rowNode, "buckets");
        if (bucketsNode == kNpos
            || nodes[bucketsNode].childCount != socket_lists::kEntryCapacity) {
            return false;
        }
        socket_entry_buckets::Definition definition{};
        definition.socketEntryListIndex = static_cast<std::uint16_t>(socketEntryListIndex);
        for (std::size_t entry = 0; entry < socket_lists::kEntryCapacity; ++entry) {
            std::uint64_t bucket = 0;
            if (!element_number(nodes, bucketsNode, entry, bucket, 0xFF)) {
                return false;
            }
            definition.buckets[entry] = static_cast<std::uint8_t>(bucket);
        }
        output.rows[output.count++] = definition;
    }
    return true;
}

/** Swaps the resolved entry-bucket rows in from the JSON. */
[[nodiscard]] bool swap_socket_entry_bucket_rows(std::span<Node> nodes,
                                                 std::size_t rowsNode) noexcept {
    static SocketEntryBucketRows parsed{};
    if (!parse_socket_entry_bucket_rows(nodes, rowsNode, parsed)) {
        report_fail("socketEntryBuckets", "parse");
        return false;
    }
    report_swap("socketEntryBuckets", parsed.count, 0, true);
    if (!socket_entry_buckets::replace(std::span(parsed.rows).first(parsed.count))) {
        report_fail("socketEntryBuckets", "reject");
        return false;
    }
    return true;
}

/** Swaps the ability-bucket rows from the JSON, stopping the boot on any contradiction. */
[[nodiscard]] bool swap_ability_rows(std::span<Node> nodes, std::size_t rowsNode) noexcept {
    static AbilityRows parsed{};
    static std::array<abilities::Definition, abilities::kDefinitionCapacity> cached{};
    if (!parse_ability_rows(nodes, rowsNode, parsed)) {
        report_fail("abilityBuckets", "parse");
        return false;
    }
    std::size_t cachedCount = 0;
    const bool match =
        abilities::snapshot(cached, cachedCount)
        && rows_match(parsed.rows.data(),
                      parsed.count,
                      cached.data(),
                      cachedCount,
                      ability_rows_equal);
    report_swap("abilityBuckets", parsed.count, cachedCount, match);
    // The ability-bucket domain is account-derived (authored characters -> subclass list ->
    // pool walk). A JSON that contradicts the cache means it was computed for different
    // characters; force-merging would corrupt the runtime, so the boot stops with the diff.
    if (!match) {
        report_ability_diff(parsed, cached, cachedCount);
        return false;
    }
    if (!abilities::replace(std::span(parsed.rows).first(parsed.count))) {
        report_fail("abilityBuckets", "reject");
        return false;
    }
    return true;
}

/** Swaps the progression rows from the JSON over the cache rows. */
[[nodiscard]] bool swap_progressions(std::span<Node> nodes, std::size_t rowsNode) noexcept {    static ProgressionRows parsed{};
    static std::array<progressions::Definition, progressions::kDefinitionCapacity> cached{};
    if (!parse_progressions(nodes, rowsNode, parsed)) {
        report_fail("progressions", "parse");
        return false;
    }
    std::size_t cachedCount = 0;
    const bool match =
        progressions::snapshot(cached, cachedCount)
        && rows_match(parsed.rows.data(),
                      parsed.count,
                      cached.data(),
                      cachedCount,
                      progression_rows_equal);
    report_swap("progressions", parsed.count, cachedCount, match);
    if (!progressions::replace(std::span(parsed.rows).first(parsed.count))) {
        report_fail("progressions", "reject");
        return false;
    }
    return true;
}

/** Reads one whole domain file into fixed storage. */
[[nodiscard]] bool read_file(const core::path::Buffer& directory,
                             std::wstring_view name,
                             std::span<char> output,
                             std::size_t& size) noexcept {
    core::path::Buffer path = directory;
    if (!core::path::append(path, name)) {
        return false;
    }
    const HANDLE file = CreateFileW(path.chars.data(),
                                    GENERIC_READ,
                                    FILE_SHARE_READ,
                                    nullptr,
                                    OPEN_EXISTING,
                                    FILE_ATTRIBUTE_NORMAL,
                                    nullptr);
    if (file == INVALID_HANDLE_VALUE) {
        return false;
    }
    LARGE_INTEGER fileSize{};
    bool ok = GetFileSizeEx(file, &fileSize) != FALSE && fileSize.QuadPart > 0
              && static_cast<std::uint64_t>(fileSize.QuadPart) <= output.size();
    DWORD read = 0;
    if (ok) {
        ok = ReadFile(file,
                      output.data(),
                      static_cast<DWORD>(fileSize.QuadPart),
                      &read,
                      nullptr)
                 != FALSE
             && read == static_cast<DWORD>(fileSize.QuadPart);
    }
    const bool closed = CloseHandle(file) != FALSE;
    if (!ok || !closed) {
        return false;
    }
    size = read;
    return true;
}

/** Parses one domain file and swaps its runtime rows. */
[[nodiscard]] bool swap_domain(const core::path::Buffer& directory,
                               const DomainFile& domain) noexcept {
    std::array<char, kJsonCapacity> buffer{};
    std::size_t size = 0;
    if (!read_file(directory, domain.file, buffer, size)) {
        core::path::Buffer path = directory;
        (void)core::path::append(path, domain.file);
        std::array<char, 640> line{};
        std::size_t used = 0;
        const int head = std::snprintf(line.data(),
                                       line.size(),
                                       "ev=s1_loader stage=swap domain=%.*s result=fail "
                                       "reason=file error=%lu path=",
                                       static_cast<int>(domain.name.size()),
                                       domain.name.data(),
                                       static_cast<unsigned long>(GetLastError()));
        if (head > 0) {
            used = static_cast<std::size_t>(head);
        }
        for (std::size_t index = 0; index < path.length && used + 1 < line.size(); ++index) {
            const wchar_t wide = path.chars[index];
            line[used++] = wide < 128 ? static_cast<char>(wide) : '?';
        }
        if (used != 0) {
            report({line.data(), used});
        }
        return false;
    }
    // The arena is too large for the stack (262k nodes); a static keeps it off the frame.
    static std::array<Node, kNodeCapacity> nodes{};
    Parser parser(std::string_view(buffer.data(), size), nodes);
    std::size_t root = 0;
    if (!parser.parse(root)) {
        std::array<char, 192> line{};
        const int written = std::snprintf(
            line.data(),
            line.size(),
            "ev=s1_loader stage=swap domain=%.*s result=fail reason=parse pos=%zu byte=%u",
            static_cast<int>(domain.name.size()),
            domain.name.data(),
            parser.position(),
            static_cast<unsigned>(parser.byte_at(parser.position())));
        if (written > 0) {
            report({line.data(), static_cast<std::size_t>(written)});
        }
        return false;
    }
    const std::size_t rowsNode = find_member(nodes, root, "rows");
    if (rowsNode == kNpos || nodes[rowsNode].kind != Node::Kind::array) {
        report_fail(domain.name, "rows");
        return false;
    }
    switch (domain.kind) {
    case DomainFile::Kind::inventoryBuckets:
        return swap_buckets(nodes, rowsNode);
    case DomainFile::Kind::socketEntryLists:
        return swap_socket_lists(nodes, rowsNode);
    case DomainFile::Kind::socketEntryTables:
        return swap_entry_tables(nodes, rowsNode);
    case DomainFile::Kind::socketEntryBuckets:
        return swap_socket_entry_bucket_rows(nodes, rowsNode);
    case DomainFile::Kind::abilityBuckets:
        return swap_ability_rows(nodes, rowsNode);
    case DomainFile::Kind::progressions:
        return swap_progressions(nodes, rowsNode);
    }
    return false;
}

/** Resolves the content directory: the configured path, else `<exe>\content`. */
[[nodiscard]] bool resolve_content_directory(void* module, core::path::Buffer& output) noexcept {
    const std::wstring_view configured(core::settings::get().server.contentDir.data());
    if (!configured.empty()) {
        return core::path::assign(output, configured);
    }
    return module != nullptr && core::path::module_directory(module, output)
           && core::path::append(output, L"\\content");
}

} // namespace

/** Applies the S1-3 Option-B oracle swap after the last cache::load. */
bool apply_oracle_swap(void* module) noexcept {
    core::path::Buffer directory;
    if (!resolve_content_directory(module, directory)) {
        report_fail("content", "path");
        return false;
    }
    for (const DomainFile& domain : kDomainFiles) {
        if (!swap_domain(directory, domain)) {
            return false;
        }
    }
    return true;
}

} // namespace sunrise::server::content
